title: Yeachan Park  # You can add your name here

description: Postdoctoral research fellow in KIAS.  # Fix hyphenation 

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal  # light
classes: wide
plugins:
  - jekyll-seo-tag # Add SEO plugin
  - jekyll-sitemap
  - jekyll-paginate



social-network-links:
  email: "ychpark@kias.re.kr"
  google-scholar: G-EEuLQAAAAJ
