title: Yeachan Park  # You can add your name here

logo: 1.png # Use a relative path to logo image 

description: AI Researcher in KIAS - where bytes and botany blend for a better world. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: ychpark@kias.re.kr # Allow visitors to contact you
