title: Yeachan Park  # You can add your name here

description: AI Researcher in KIAS - where bytes and botany blend for a better world. # Fix hyphenation 

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: 



links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: ychpark@kias.re.kr
